Message.create(content: 'This is the 1st sample')
Message.create(content: 'Good morning, am Topaz')
Message.create(content: 'Good afternoon, this is topas ')
Message.create(content: 'Good  Everning, nice to meet you')
Message.create(content: 'Hello world, this is topas')